install.packages("BiocManager")
BiocManager::install("graph")
BiocManager::install("RBGL")
BiocManager::install("Rgraphviz")
install.packages(c(
    "dagitty",
    "remotes",
    "pROC",
    "naivebayes",
    "ranger",
    "bnlearn",
    "lavaan",
    "readr",
    "Hmisc",
    "icesTAF",
    "BiocManager",
    "sets",
    "pcalg",
    "NetworkDistance"
))
remotes::install_github("jtextor/bayesianNetworks")
