install.packages(c(
    "dagitty",
    "remotes",
    "pROC",
    "naivebayes",
    "ranger",
    "bnlearn",
    "lavaan",
    "readr",
    "Hmisc",
    "icesTAF",
    "BiocManager"
))
BiocManager::install("graph")
BiocManager::install("RBGL")
BiocManager::install("RGraphviz")
install.packages("pcalg")
remotes::install_github("jtextor/bayesianNetworks")
