install.packages(c(
    "dagitty",
    "remotes",
    "pROC",
    "naivebayes",
    "ranger",
    "bnlearn",
    "lavaan",
    "readr",
    "Hmisc",
    "icesTAF"
))
remotes::install_github("jtextor/bayesianNetworks")
